# Generated by Django 6.0.5 on 2026-07-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('productos', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='empleado',
        ),
        migrations.AddField(
            model_name='ventas',
            name='folio',
            field=models.CharField(default='V-001', max_length=50),
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.AlterField(
            model_name='ventas',
            name='total',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='ventas',
            name='cliente',
            field=models.ManyToManyField(to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='producto',
            field=models.ManyToManyField(to='productos.producto'),
        ),
    ]
