# Generated by Django 6.0.5 on 2026-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_remove_ventas_cantidad_remove_ventas_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventas',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
