# Generated by Django 6.0.5 on 2026-07-08 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_nomina'),
    ]

    operations = [
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numperiodo', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('salario', models.FloatField()),
                ('perceciones', models.FloatField()),
                ('deducciones', models.FloatField()),
                ('total', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='empleados.empleado')),
            ],
        ),
    ]
