# Generated by Django 6.0.5 on 2026-07-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_estatus_alter_nomina_empleado_and_more'),
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomina',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina_nominas', to='empleados.empleado'),
        ),
    ]
