# Generated by Django 6.0.5 on 2026-07-14 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_sexo_delete_nomina'),
        ('nomina', '0002_nomina_estatus_alter_nomina_empleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='empleados.empleado'),
        ),
    ]
