# Generated by Django 6.0.5 on 2026-07-01 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numperiodo', models.CharField()),
                ('fecha', models.DateField()),
                ('salario', models.FloatField()),
                ('percepciones', models.FloatField()),
                ('deducciones', models.FloatField()),
                ('total', models.FloatField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomina', to='empleados.empleado')),
            ],
        ),
    ]
