# Generated by Django 6.0.5 on 2026-07-12 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_nominas', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='nomina',
            name='numperiodo',
            field=models.CharField(max_length=50),
        ),
    ]
