# Generated by Django 6.0.5 on 2026-07-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_estatus_alter_nomina_empleado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='nomina',
        ),
    ]
