# Generated by Django 6.0.5 on 2026-07-15 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_empleado_sexo_delete_nomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_base',
            field=models.FloatField(default=0.0),
        ),
    ]
