# Generated by Django 6.0.5 on 2026-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
