# Generated by Django 6.0.5 on 2026-07-15 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0002_inventarios_estatus'),
        ('productos', '0002_producto_estatus'),
        ('proveedores', '0003_productos_estatus_proveedores_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='producto_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
        migrations.AddField(
            model_name='inventarios',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedores.proveedores'),
        ),
        migrations.AddField(
            model_name='inventarios',
            name='ubicacion',
            field=models.CharField(default='Almacén General', max_length=100),
        ),
    ]
