# Generated by Django 6.0.5 on 2026-07-16 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_inventarios_producto_relacionado_and_more'),
        ('sucursal', '0002_sucursal_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarios',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucursal.sucursal'),
        ),
    ]
