# Generated by Django 6.0.5 on 2026-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucursal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
