# Generated by Django 6.0.5 on 2026-07-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
        ('productos', '0001_initial'),
        ('proveedores', '0002_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(default='C-001', max_length=50)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('subtotal', models.FloatField(default=0.0)),
                ('iva', models.FloatField(default=0.0)),
                ('total', models.FloatField(default=0.0)),
                ('producto', models.ManyToManyField(to='productos.producto')),
                ('proveedor', models.ManyToManyField(to='proveedores.proveedores')),
            ],
        ),
        migrations.DeleteModel(
            name='compra',
        ),
    ]
