# Generated by Django 6.0.5 on 2026-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_compras_delete_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateField(),
        ),
    ]
