# Generated by Django 6.0.5 on 2026-07-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_compras_estatus_alter_compras_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
