# Generated by Django 6.0.5 on 2026-07-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('color', models.CharField(max_length=1000)),
            ],
        ),
    ]
