# Generated by Django 6.0.5 on 2026-07-12 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='estatus',
            field=models.BooleanField(default=True),
        ),
    ]
